#!/bin/bash

#a simple script for interminent testing 
python3 server.py Johnson &


sleep .5s
time_1=`date +%s` 
python3 client.py 10394 "IAMAT Eyal +32.091912+34.785292 ${time_1}" 
python3 client.py 10394 "WHATSAT Eyal 1 1" 
sleep 4s #let things occuer
echo '----------------------------'
pkill -f server.py #?try to kill the servers in case of failure, ussuly this yields errs, but that's ok 
echo '----------------------------'

# netstat -tulpn | grep 1039 to find my ports in use
# then kill pid